In [1]:
from quantrocket.history import get_historical_prices
import quantrocket.db
from quantrocket import *


#Variables

universe = "australia-stk"
db = "end-auction-day"
start_date = "2019-01-02"
end_date = "2019-01-25"



prices = get_historical_prices(db, 
                               start_date=start_date,
                               end_date=end_date, 
                               universes=universe,
                               fields=["High", "Low", "Open", "Close"])


new_prices = prices[prices.loc["Open"] >= 0.1]

opens = new_prices.loc["Open"]
closes = new_prices.loc["Close"]
highs = new_prices.loc["High"] 
lows = new_prices.loc["Low"]

dollar_change = (highs - lows)

#dollar_change.head()

dollar_change_percentage = (dollar_change / ((opens+closes)/2)) * 100

#dollar_change_percentage.head()


dollar_change_percentage_sorted = dollar_change_percentage.sort_values(by=start_date, axis=1, ascending=False)

dollar_change_percentage_sorted.head(50)

dollar_change_percentage_sorted.describe()

ConId,347787870,44200608,135931764,44205079,317233168,44187521,147967929,340927523,252322615,139462947,...,345526135,345786611,346216377,348087382,349593258,349593265,349593316,349966803,350190255,351020231
count,18.000000,18.000000,18.000000,18.000000,18.000000,18.000000,16.000000,8.000000,16.000000,15.000000,...,0.0,15.000000,7.000000,0.0,0.0,0.0,0.0,11.000000,0.0,3.000000
mean,11.697297,6.641622,8.101409,6.333961,7.917350,7.471396,5.136972,3.611680,6.080069,3.314082,...,NaN,5.083038,4.765022,NaN,NaN,NaN,NaN,0.842352,NaN,0.104274
std,10.067961,5.049500,7.110572,4.781639,4.046164,4.510316,6.844021,6.768003,3.309901,5.505541,...,NaN,4.983095,4.785273,NaN,NaN,NaN,NaN,1.217162,NaN,0.119363
min,2.222222,3.125000,0.000000,2.777778,3.505155,0.000000,0.000000,0.000000,1.886792,0.000000,...,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,0.000000
25%,5.030998,3.187404,3.621968,2.898551,5.222455,5.211893,0.000000,0.000000,3.805010,0.000000,...,NaN,1.098901,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN,0.039177
50%,7.911392,5.971480,6.838106,5.039124,6.631046,6.217784,1.627738,0.000000,5.444444,0.000000,...,NaN,5.128205,4.651163,NaN,NaN,NaN,NaN,0.364299,NaN,0.078355
75%,15.998508,8.161083,9.680451,7.857143,9.831512,8.605072,9.001078,3.125000,7.166781,5.734369,...,NaN,6.488193,9.473947,NaN,NaN,NaN,NaN,1.335837,NaN,0.156411
max,35.820896,24.615385,24.561404,20.000000,18.478261,18.421053,21.192053,16.393443,15.165877,15.094340,...,NaN,18.390805,9.756098,NaN,NaN,NaN,NaN,3.584229,NaN,0.234467