In [3]:
from quantrocket.history import get_historical_prices
import quantrocket.db
from quantrocket import *
from pandas import *

universe = "cba"
db = "end-auction-cba"
start_date = "2019-01-14"
end_date = "2019-01-25"

prices = get_historical_prices(db, 
                               start_date=start_date,
                               end_date=end_date, 
                               universes=universe,
                               fields=["High", "Low", "Open", "Close"])

start_auction = prices.xs("16:00:00", level="Time")
end_auction = prices.xs("16:10:00", level="Time")

highs = prices.loc["High"] 
lows = prices.loc["Low"]
opens = prices.loc["Open"]
closes = prices.loc["Close"]

#day_avg = (opens + closes)/2

dollar_change = (end_auction - start_auction)


#dollar_change_percentage = (dollar_change/((opens + closes)/2)) * 100
#prices.head(60)
dollar_change.head(60)
#dollar_change.describe()
#dollar_change_percentage.head(60)

ConId               4036818
Field    Date
Close    2019-01-14   -0.06
         2019-01-15   -0.07
         2019-01-16    0.15
         2019-01-18   -0.08
         2019-01-21   -0.14
         2019-01-22   0.006
         2019-01-23    0.15
         2019-01-25    -0.1
High     2019-01-14   3.898
         2019-01-15   3.241
         2019-01-16    1.37
         2019-01-18   2.342
         2019-01-21   2.322
         2019-01-22   5.636
         2019-01-23   5.118
         2019-01-25   3.382
Low      2019-01-14   -0.04
         2019-01-15   -0.02
         2019-01-16     0.2
         2019-01-18   -0.02
         2019-01-21   -0.09
         2019-01-22    0.08
         2019-01-23    0.19
         2019-01-25   -0.11
Open     2019-01-14   3.943
         2019-01-15   3.241
         2019-01-16    1.37
         2019-01-18   2.342
         2019-01-21   2.401
         2019-01-22   5.636
         2019-01-23   5.118
         2019-01-25   3.382
Timezone 2019-01-14     NaN